sudo: required
dist: trusty
language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - mono
    packages:
    - ghc
    - gnat
    - php5-cli
    - mono-devel
    - mono-vbnc
    - fsharp
    - fp-compiler
    - coffeescript
    - binutils-multiarch
    - libc6-dev-i386
    - nasm
    - open-cobol
    - lua5.2
    - gfortran
before_install:
  # Install Swift
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/ubuntu1404/swift-2.2-SNAPSHOT-2015-12-22-a/swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04.tar.gz
  - tar xzf swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04/usr/bin:"${PATH}"
  # Install Rust
  - curl -sSf https://static.rust-lang.org/rustup.sh | sh
  # Install latest Scala
  - wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb
  - sudo dpkg -i scala-2.11.8.deb
  # Install D
  - wget http://downloads.dlang.org/releases/2.x/2.071.1/dmd_2.071.1-0_amd64.deb
  - sudo dpkg -i dmd_2.071.1-0_amd64.deb
  # Install sdkman for Groovy and Kotlin
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  # Install Groovy
  - yes | sdk install groovy
  - export PATH=$HOME/.sdkman/candidates/groovy/current/bin:"${PATH}"
  # Install Dart
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart/stable
  # Install R
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install r-base
install:
  - pip install codecov
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop
  - mkdir testsuite && curl https://codeload.github.com/DMOJ/judge-testsuite/legacy.tar.gz/master | tar xz -C testsuite --strip-components=1
script:
  - coverage run --source=dmoj .travis.test.py
after_script:
  - codecov
notifications:
  - slack: dmoj:kfSyzQoO51WwR2MFvfRAhUxD
