language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - ghc
    - gnat
    - php5-cli
install:
  - pip install coveralls
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop 
script:
  - python .travis.test.py
  - coverage run .travis.test.py
after_success:
  coveralls
