language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - ghc
    - gnat
    - php5-cli
    - oracle-java8-installer
    - scala
install:
  - pip install coveralls
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop 
script:
  coverage run --source=dmoj .travis.test.py
after_script:
  coveralls
