sudo: required
dist: trusty
language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - mono
    packages:
    - ghc
    - gnat
    - php5-cli
    - mono-devel
    - mono-vbnc
    - fsharp
    - fp-compiler
    - coffeescript
    - binutils-multiarch
    - libc6-dev-i386
    - nasm
    - open-cobol
before_install:
  # Install Swift
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/ubuntu1404/swift-2.2-SNAPSHOT-2015-12-22-a/swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04.tar.gz
  - tar xzf swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-2.2-SNAPSHOT-2015-12-22-a-ubuntu14.04/usr/bin:"${PATH}"
  # Install Rust
  - curl -sSf https://static.rust-lang.org/rustup.sh | sh
  # Install latest Scala
  - wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb
  - sudo dpkg -i scala-2.11.8.deb
  # Install D
  - curl -sSf https://dlang.org/install.sh | bash -s dmd
  # Install sdkman for Groovy and Kotlin
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  # Install Groovy
  - sdk install groovy
install:
  - pip install codecov
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop
  - mkdir testsuite && curl https://codeload.github.com/DMOJ/judge-testsuite/legacy.tar.gz/master | tar xz -C testsuite --strip-components=1
script:
  - coverage run --source=dmoj .travis.test.py
after_script:
  - codecov
notifications:
  - slack: dmoj:kfSyzQoO51WwR2MFvfRAhUxD
