language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - mono
    - mono-libtiff-compat
    packages:
    - gcc-5
    - g++-5
    - ghc
    - gnat
    - php5-cli
    - oracle-java8-installer
    - scala
    - mono-devel
    - mono-vbnc
    - fsharp
    - coffeescript
    - binutils-multiarch
    - libc6-dev-i386
    - nasm
install:
  - pip install coveralls
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop 
script:
  coverage run --source=dmoj .travis.test.py
after_script:
  coveralls
notifications:
  slack: dmoj:kfSyzQoO51WwR2MFvfRAhUxD
