sudo: required
dist: trusty
language: python
python:
  - 2.7
addons:
  apt:
    sources:
    - mono
    - mono-libtiff-compat
    packages:
    - ghc
    - gnat
    - php5-cli
    - oracle-java8-installer
    - scala
    - mono-devel
    - mono-vbnc
    - fsharp
    - coffeescript
    - binutils-multiarch
    - libc6-dev-i386
    - nasm
install:
  - pip install codecov
  - pip install Cython --install-option="--no-cython-compile"
  - python setup.py develop
  - mkdir testsuite && curl https://codeload.github.com/DMOJ/judge-testsuite/legacy.tar.gz/master | tar xz -C testsuite --strip-components=1
script:
  - coverage run --source=dmoj .travis.test.py
after_script:
  - codecov
notifications:
  - slack: dmoj:kfSyzQoO51WwR2MFvfRAhUxD
